### ISSUE TITLE
How to set

### ISSUE THREAD

**Issue by sirxsniper** [woah1337/NSLoader#1]

**Comment by cojo1989** [comment]
@woah1337 I would love to see a tutorial how to set it. It`s dope <3

**Comment by woah1337** [comment]
Uh il make a video tutorial tomorrow, its fairly simple tho everything is in settings.cs.

**Comment by cojo1989** [comment]
The problem is php files. I got error on them. Every problem of mine is starting from php and ini files.

**Comment by cojo1989** [comment]
You dont have any php or web parts on git.

**Comment by woah1337** [comment]
Use the one from roshly's Github - https://github.com/Roshly/AyyHook-Loader/blob/master/Ayyhook%20Web%20Files/check.php.
I'll update the repo tomorrow with a non vulnerable web file (you can easily hack thaisen/roshly's PHP files using sqlmap because of the hwid update thing) but till then that should work.

**Comment by cojo1989** [comment]
I just need for me and my friends. But if you can upload on git everything it would be perfect. Keep the good job buddy i love you :)

**Comment by cojo1989** [comment]
@woah1337 I resolve, it`s working perfect but it`s crashing my csgo... if I inject it normaly with a simple injector it`s working perfect. When i put the injector from loader it`s crashing...

**Comment by woah1337** [comment]
It was working fine for me with everything but Osiris, what were you using? I'll inject and debug.

**Comment by cojo1989** [comment]
I tryed with Osiris too... for me it`s crashing... Maybe i need to make some settings to manual map injection?

**Comment by woah1337** [comment]
Added Blackbone injection and a check to make sure CSGO is loaded before injection, tested it with eternity.cc.
This should fix your problem.
First compile injectlib, copy injectlib.dll to the same folder as the loader then compile the loader and inject.

**Comment by woah1337** [comment]
Joined discord so closed
